name: Build Deb
on:
  workflow_dispatch:
  push:
#  release:

# required for uploading assets
permissions:
  contents: write

jobs:
  deb:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Deb
        run: |
          sudo apt-get install -y debhelper dh-python build-essential python3-pyqt5 pyqt5-dev-tools
          sudo pip3 install --upgrade setuptools --break-system-packages
          sudo pip3 install --upgrade pip --break-system-packages
          pip list
          dpkg-buildpackage -uc -us
          mv ../*.deb .

      - uses: pozetroninc/github-action-get-latest-release@master
        id: latest-tag
        with:
          repository: ${{ github.repository }}

      - name: Upload Release Assets
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "*.deb"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ steps.latest-tag.outputs.release }}

