name: Build
on:
  push:
  workflow_dispatch:
#  release:

# required for uploading assets
permissions:
  contents: write

jobs:
  AppImage:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v3

      - name: Build AppImage
        run: |
          cd AppImage
          bash -ex build-in-docker.sh

      - uses: pozetroninc/github-action-get-latest-release@master
        id: latest-tag
        with:
          repository: ${{ github.repository }}

      - name: Upload Release Assets
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "AppImage/ChemCanvas-x86_64.AppImage"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ steps.latest-tag.outputs.release }}

